version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - OLLAMA_HOST=ollama
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ragdb
    depends_on:
      - db
      - ollama

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # 로컬 파일과 동기화
      - ./frontend/node_modules:/app/node_modules  # node_modules 충돌 방지
    environment:
      - CHOKIDAR_USEPOLLING=true  # 파일 변경 감지
      - WATCHPACK_POLLING=true  # Webpack 감지 활성화
    stdin_open: true  # 컨테이너에서 입력을 받을 수 있도록 설정
    tty: true  # 터미널 인터페이스 활성화
    depends_on:
     - backend

  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  ollama:
    build: ./ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  postgres-data:
  ollama-data:
